### ISSUE TITLE
grepolis tools

### ISSUE THREAD

**Issue by TXADOW** [MLescaudron/chrome-extension-grepolis-tools#1]
not working animore
i press start buton, but de cooldown dont move

**Comment by TheFamousPG** [comment]
Thanks for the reply.

I just tested it and it worked fine.
Can you re-try?
If you have again problems, thank you for sending me a screen shot.


Best Regards


*Mathieu Lescaudron*
47C rue marietton
69009 LYON

2016-02-16 1:21 GMT+01:00 TXADOW <notifications@github.com>:

**Comment by TXADOW** [comment]
https://gyazo.com/60d549e75359819f64351c0b6d58c8d2

**Comment by TXADOW** [comment]
its just for me its not working?

**Comment by TXADOW** [comment]
so? can u tell me what can i do 2 fix it?

**Comment by TheFamousPG** [comment]
Try to update Google Chrome.
Have you any others extensions ?

**Comment by TXADOW** [comment]
i already delet cookies and histo and its the same. yhes i have tampermonkey and adblock

**Comment by TheFamousPG** [comment]
When you install the extension, do you have the success message ?

**Comment by TXADOW** [comment]
yes:
https://gyazo.com/d86caefbc9bb52b8cc74d5a8c8be4185

**Comment by TheFamousPG** [comment]
Do you have any error in console tab ? (F12)

**Comment by TXADOW** [comment]
yes i have 13 http://prntscr.com/a6z1uu

**Comment by TheFamousPG** [comment]
Can you send me this error. (In the console tab)

**Comment by TXADOW** [comment]
its this? http://prntscr.com/a6z3vv

**Comment by TheFamousPG** [comment]
Exactly this. Can you send me your url.
And your language grepolis version + grepolis server.
I notified you saturday.

**Comment by TXADOW** [comment]
game url: https://pt34.grepolis.com/game/index?login=1&p=571015&ts=1454970633
grepolis version: Wednesday its gona be 2.106
grepolis server: pt34.grepolis.com

**Comment by TheFamousPG** [comment]
Try this : http://stackoverflow.com/questions/25814914/chrome-youtube-cast-sender-js-console-error

**Comment by TXADOW** [comment]
sorry but not I realized what it was to do

**Comment by TheFamousPG** [comment]
Apparently, in you have a cast_sender error.
In the url, they sey it's google chromecast.
Can you try to install the Google Cast extension

**Comment by TXADOW** [comment]
i have istaled google cast, and keep not working

**Comment by TXADOW** [comment]
but now i just have 1 error. and is this: 
http://prntscr.com/a70vqx

**Comment by TheFamousPG** [comment]
Try to reinstall the extension. If the problem persist, it's because of grepolis.... I try to solved your problem satudray

**Comment by TXADOW** [comment]
ok then i will reinstall and after i give u feedback

**Comment by TXADOW** [comment]
keep not working :/

**Comment by TheFamousPG** [comment]
Ok. I try to create an account on this serveur saturday to test it.

**Comment by TXADOW** [comment]
and it have work?

**Comment by TXADOW** [comment]
ou can not create a quickly now?

**Comment by TheFamousPG** [comment]
I'm at school actually. Sry.
8h > 22h this week

**Comment by TXADOW** [comment]
ok then i will wait

**Comment by TheFamousPG** [comment]
Work fine for me...
https://gyazo.com/ca7e28a714e441ffe22060977961690b

Try to entire clear your cache
https://gyazo.com/034e19a1d42b76a42974608283ba5f58

How many cities you have and how many farm town ?
Are you sure to use the last google chrome browser ?

**Comment by TXADOW** [comment]
i have 4 cities and on total i have 17 farm town
how do i see iff its the last version of google chrome?

**Comment by TheFamousPG** [comment]
https://gyazo.com/c6d153678b8f4b19b824b40d0d4601b4

**Comment by TXADOW** [comment]
yes, is updated

**Comment by TheFamousPG** [comment]
I do not know why you have this problem...
Can you try to create a new account for testing and try to test the extension ?

**Comment by TheFamousPG** [comment]
@TXADOW I updated the extension tell me if it works now pls.

**Comment by MLescaudron** [comment]
I consider the absence of your response that the issue is resolved.
